---
- name: Update Usernames to All Caps convention
  hosts: all
  become: yes
  vars: 
    users: 
      robert:
        rename: no
        old_name: admin_rwatkins
        new_name: rwatkins
        ssh: true
        ssh_key: # ansible test key
        
      kraj:
        rename: no
        old_name: admin_kraj
        new_name: kraj
        ssh: true
        ssh_key: # ansible test key
        
      davis:  
        rename: no
        old_name: admin_davis
        new_name: davis
        ssh: true
        ssh_key: # ansible test key
        
      kevin:  
        rename: no
        old_name: admin_kevin
        new_name: kevin
        ssh: false
        ssh_key: # ansible test key
      
      jackie:  
        rename: no
        old_name: admin_jackie
        new_name: jackie
        ssh: false
        ssh_key: # ansible test key
      
    
  
  tasks:
  #- name: Get list of current users with admin_
  #    shell: cat /etc/passwd | awk -F ':' '{print $1}' | grep admin_*
  #  register: admins
  #  
  #- name: Check if admin_s are logged in
  #    shell: w | grep admin_* | awk something
  #  register: logged_in_admins
  #  
  #- name: remove them from list if they are logged in
  #  set_fact: 
  #    admins: something? 
  #  
  
  #- name: Check if admin_ users exist
  #  command: "awk -F: '$3 >= 1000 { print $1}' /etc/passwd | grep -v nobody | grep admin_ | sed -z 's/\n/,/g'"
  #  register: admin_users
    
  - name: Set rename var
    debug:
      msg: "{{ item }}"
    with_lines: ls /home/
    #with_lines: "awk -F: '$3 >= 1000 { print $1}' /etc/passwd | grep -v nobody | grep admin_ "
    
  
  - name: Make changes
    block:
      - name: Move home directory
        user:
          name: "{{ item.value.old_name }}"
          home: "/home/{{ item.value.new_name }}"
          move_home: yes
        loop: "{{ lookup('dict', users) }}"
        
      - name: Rename Users
        command: usermod --login "{{ item.value.new_name }}" "{{ item.value.old_name }}"
        loop: "{{ lookup('dict', users) }}"
    
      - name: Install ssh key
        authorized_key:
          user: "{{ item.value.new_name }}"
          key: "{{ item.value.ssh_key }}"
          state: present
        when: item.value.ssh
        loop: "{{ lookup('dict', users) }}"
        
    #when: