---
- name: Update Usernames to All Caps convention
  hosts: all
  remote_user: merlin
  vars: 
    users: 
      admin_rwatkins:
        new_name: rwatkins
        ssh_key: #path or key
        
      admin_kraj:
        new_name: kraj
        ssh_key: #path or key
        
      admin_davis:
        new_name: davis
        ssh_key: #path or key
        
      admin_kevin:
        new_name: kevin
        ssh_key: #path or key
        
      admin_jackie:
        new_name: jackie
        ssh_key: #path or key
      
    
  
  tasks:
  - name: Get list of current users with admin_
      shell: cat /etc/passwd | awk -F ':' '{print $1}' | grep admin_*
    register: admins
    
  - name: Check if admin_s are logged in
      shell: w | grep admin_* | awk something
    register: logged_in_admins
    
  - name: remove them from list if they are logged in
    set_fact: 
      admins: something? 
    
  - name: Rename Users
      shell: usermod -l {{ item.value.new_name }} {{ item.value.old_name }}
    loop: "{{ lookup('dict', users) }}"
    
  - name: Rename Home Folder
      shell