' ---
- name: Update Usernames to All Caps convention
  hosts: all
  become: yes
  vars: 
    users: 
      robert:
        rename: no
        old_name: admin_rwatkins
        new_name: rwatkins
        ssh: true
        ssh_key: # ansible test key
        
      kraj:
        rename: no
        old_name: admin_kraj
        new_name: kraj
        ssh: true
        ssh_key: # ansible test key
        
      davis:  
        rename: no
        old_name: admin_davis
        new_name: davis
        ssh: true
        ssh_key: # ansible test key
        
      kevin:  
        rename: no
        old_name: admin_kevin
        new_name: kevin
        ssh: false
        ssh_key: # ansible test key
      
      jackie:  
        rename: no
        old_name: admin_jackie
        new_name: jackie
        ssh: false
        ssh_key: # ansible test key
      
      blue:
        rename: no
        old_name: orange
        new_name: blue
        ssh: true
        ssh_key: # ansible test key
      
    
  
  tasks:
  
   - name: Check for admin users
    command: grep "{{ item.value.old_name }}" /etc/passwd
    register: found
    check_mode: no
    ignore_errors: yes
    changed_when: no
    loop: "{{ lookup('dict', users) }}"

  - name: Output when found
    debug: msg="Hello, world!"
    when: found.rc == 0
  
  - name: Make changes
    block:
      - name: Move home directory
        user:
          name: "{{ item.value.old_name }}"
          home: "/home/{{ item.value.new_name }}"
          move_home: yes
        loop: "{{ lookup('dict', users) }}"
        
      - name: Rename Users
        command: usermod --login "{{ item.value.new_name }}" "{{ item.value.old_name }}"
        loop: "{{ lookup('dict', users) }}"
    
      - name: Install ssh key
        authorized_key:
          user: "{{ item.value.new_name }}"
          key: "{{ item.value.ssh_key }}"
          state: present
        when: item.value.ssh
        loop: "{{ lookup('dict', users) }}"
    ignore_errors: yes
    #when: