---
- name: Update Usernames to All Caps convention
  hosts: all
  become: yes
  vars: 
    users: 
      robert:
        old_name: admin_rwatkins
        new_name: rwatkins
        ssh_key: #path or key
        
      kraj:
        old_name: admin_kraj
        new_name: kraj
        ssh_key: #path or key
        
      davis:  
        old_name: admin_davis
        new_name: davis
        ssh_key: #path or key
        
      kevin:  
        old_name: admin_kevin
        new_name: kevin
        ssh_key: #path or key
      
      jackie:  
        old_name: admin_jackie
        new_name: jackie
        ssh_key: #path or key
      
    
  
  tasks:
  - name: Remove all caps if present
    user:
      name: "{{ item.value.new_name }}"
      state: absent
    ignore_errors: yes
    loop: "{{ lookup('dict', users) }}"
    
  - name: remove old users if present
    user:
      name: "{{ item.value.old_name }}"
      state: absent
    ignore_errors: yes
    loop: "{{ lookup('dict', users) }}"
    
  - name: delete old home dirs
    file: "/home/{{ item.value.old_name }}"
      state: deleted
    ignore_errors: yes
    loop: "{{ lookup('dict', users) }}"

  - name: delete new home dirs
    file: "/home/{{ item.value.new_name }}"
      state: deleted
    ignore_errors: yes
    loop: "{{ lookup('dict', users) }}"
  
  - name: Create old Users
    user:
      name: "{{ item.value.old_name }}"
      state: present
    ignore_errors: yes
    loop: "{{ lookup('dict', users) }}"
    
    
    